### ISSUE TITLE
Gutter tooltip not showing inside relative container

### ISSUE THREAD

**Issue by billyzkid** [ajaxorg/ace#1546]
I noticed when I hover over a warning/error icon in the gutter, I am not seeing the tooltips. This happens because my editor is inside a relative container and the tooltips use fixed position plus set top/left values.

I believe this can be easily fixed by using this approach: [Fixed position but relative to a container](http://stackoverflow.com/a/11833892)

**Comment by ButchMonkey** [comment]
I also had this issue but the above jsbin does not reproduce the issue anymore.
I fixed by overwriting the Tooltip setposition function and offsetting the tooltip by the top offset - 

```
         ace.require('ace/tooltip').Tooltip.prototype.setPosition = function (x, y) {
            y -= $(this.$parentNode).offset().top;
            
            this.getElement().style.left = x + "px";
            this.getElement().style.top = y + "px";
         };
```

**Comment by MishaKanai** [comment]
I'm still seeing this bug.
@ButchMonkey Thanks, that was a helpful starting point. I also had to make the element positioning absolute.
Without jquery:
`
function getElementOffset(element)
{
    const de = document.documentElement;
    const box = element.getBoundingClientRect();
    const top = box.top + window.pageYOffset - de.clientTop;
    const left = box.left + window.pageXOffset - de.clientLeft;
    return { top: top, left: left };
}

ace.require('ace/tooltip').Tooltip.prototype.setPosition = function (x, y) {
    y -= getElementOffset(this.$parentNode).top;
    x -= getElementOffset(this.$parentNode).left;
    this.getElement().style.position = "absolute";
    this.getElement().style.left = x + "px";
    this.getElement().style.top = y + "px";
 };
`
