### ISSUE TITLE
Cannot use backspace in Android Chrome

### ISSUE THREAD

**Issue by mustafaakin** [ajaxorg/ace#1671]
I cannot use backspace in Android's chrome, it doesn't delete nor move back, any ideas?

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.

**Comment by pascalaschwanden** [comment]
I just checked it on http://ace.c9.io  with my android HTC One M9 and it still doesn't work.

Expected result:
hit the backspace button on the keyboard and the character or line will delete

Actual result:
Characters are deleted but line does not wrap around to previous line.  empty lines are not deleted when you press the back space key.

**Comment by nightwing** [comment]
@pascalaschwanden what keyboard do you use?

**Comment by pascalaschwanden** [comment]
The default keyboard on Android 7.0, whatever pops up when I'm in Chrome.

thanks for the fast response.

**Comment by pascalaschwanden** [comment]
I've been working on some code to fix this problem: but it's a bit of a hack.
The tricky part is replacing the line-break with nothing, so that it eliminates it for the right line.

editor.keyBinding.addKeyboardHandler({
            //  data_before shows contents of text area before the user's keystroke.
            handleKeyboard : function(data, hash, keyString, keyCode, event) {

                //  ace.js bug: Android does not remove the newline upon delete key.
                if( keyCode === 8 ) {

                    var before = data.editor.getValue();

                    setTimeout( function() {

                        var after = editor_[id].getValue();
                        console.log( before + '  ' + after );

                        if( before === after ) {
                            //  Means editor did nothing.  Now delete one value.
                            var cursorPosition = editor_[id].getCursorPosition();
                            console.dir(cursorPosition);

                        } else {
                            console.log('diff');
                        }
                    }, 200 );
                }
            }
        });

**Comment by pascalaschwanden** [comment]
if we could just get the cursor numbered position (1 number), then it'd be an easy matter of splitting up the string and removing the return character.  but how can i get the cursor numbered position? (not row, column)

**Comment by nightwing** [comment]
@pascalaschwanden  looks like the event for backspace is not fired if cursor is at the beginning of the textarea.
Could you check if https://rawgit.com/ajaxorg/ace/textinput/kitchen-sink.html works?

**Comment by nightwing** [comment]
Thanks for checking! could you please try this version too https://rawgit.com/ajaxorg/ace/textinput-2/kitchen-sink.html (i am asking because i can't reproduce the issue on my phone).

**Comment by pascalaschwanden** [comment]
Sorry still doesn't work.

The first backspace  does work.  Then the second one undoes that backspace
then third one does nothing, etc. Moving cursor restarts that cycle

**Comment by nightwing** [comment]
Interesting. From your code in https://github.com/ajaxorg/ace/issues/1671#issuecomment-445499682 it seems that backspace key with a correct keycode is fired, but editor doesn't handle it, or somehow reverts the action. Did i understand that example correctly?

Could you please try enabling "Text Input debugger" from the sidebar, pressing backspace several times, and giving me the result from log area
![image](https://user-images.githubusercontent.com/341801/50424342-b60fd000-087b-11e9-84bb-ae6739998d61.png)
