### ISSUE TITLE
Edge autmatically adds two new lines on first character

### ISSUE THREAD

**Issue by Cellcote** [ajaxorg/ace#3784]
Version v1.4.1

I can reproduce it on https://ace.c9.io/ in Edge 42.17134.1.0. 

Click somewhere in the Ace editor, and enter a single character. 
Result: two new lines are added.

This only happens on the first focus on the editor and only on the first character. After a refresh, they can be reproduced again.

**Comment by blacktem12** [comment]
It's a temporary measure, If browser is an edge, use focus() and blow().
That will solve it.

**Comment by nightwing** [comment]
Thanks for the report, This should be fixed on the master branch https://rawgit.com/ajaxorg/ace/master/kitchen-sink.html

**Comment by Cellcote** [comment]
Thanks! But I can still reproduce it when the cursor is in the initial (top-left corner) position. Your fix seems to fix it for other cases though.

**Comment by Cellcote** [comment]
@nightwing Your new fix did fix the problem 👍
